#!/bin/bash

export CHANG_DIR=XXX
export CHANG_PROJECTS_DIR=$CHANG_DIR/projects

export PATH="$CHANG_DIR/bin:$PATH"

if [[ -n ${ZSH_VERSION:-""} ]]; then
  . $CHANG_DIR/rcscripts/changrc.zsh
elif [[ -n ${BASH_VERSION:-""} ]]; then
  . $CHANG_DIR/rcscripts/changrc.bash
fi

function chang() {
  if [ $# -eq 0 ]; then
    cd $CHANG_PROJECTS_DIR
  else
    if [ -x $CHANG_DIR/bin/chang-$1 ]; then
      $CHANG_DIR/bin/chang-$1 "${@:2}"
    else
      echo "chang $1: command not found" >&2
      return 1
    fi
  fi
}

function chang-run() {
  local project=${1:?}
  if [[ $# -eq 1 ]]; then
    cd $CHANG_PROJECTS_DIR/$project
  else
    $CHANG_DIR/bin/chang-run "${@}"
  fi
}