Vagrant.configure(2) do |config|
  config.vm.box = "chang"

  # call `vagrant box outdated` manually
  config.vm.box_check_update = false

  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.synced_folder 'vm_shared_folder', '/vm_shared_folder'

  config.vm.network "private_network", ip: "192.168.33.10"

  (2000...2010).each do |port|
    config.vm.network "forwarded_port", guest: port, host: port, ip: "0.0.0.0"
  end

  config.vm.hostname = "chang"
  config.vm.provider "virtualbox" do |v|
    v.name = "chang"
    v.memory = 4096
    v.cpus = 4
  end

  config.ssh.insert_key = false
  config.ssh.forward_agent = true
end
